export const MOTIVATIONAL_QUOTES = [
  "Well done is better than well said.",
  "What you do today can improve all your tomorrows.",
  "Action is the foundational key to all success.",
  "The secret of getting ahead is getting started.",
  "If it is important to you, you will find a way.",
  "We become what we repeatedly do.",
  "Discipline is the bridge between goals and accomplishment.",
  "Success is not final, failure is not fatal.",
  "You miss 100% of the shots you don't take.",
  "Do what you can, with what you have, where you are.",
  "The future depends on what you do today.",
  "Start where you are. Use what you have.",
  "Energy and persistence conquer all things.",
  "Motivation gets you started. Habit keeps you going.",
  "The harder the conflict, the greater the triumph.",
  "Do not wait to strike till the iron is hot.",
  "Nothing will work unless you do.",
  "Make each day your masterpiece.",
  "Success usually comes to those who are too busy to look for it.",
  "It always seems impossible until it's done.",
  "If you're going through hell, keep going.",
  "The way to get started is to quit talking and begin doing.",
  "Without discipline, there's no life at all.",
  "A goal is a dream with a deadline.",
  "What we fear doing most is usually what we most need to do.",
  "Quality is not an act, it is a habit.",
  "Do one thing every day that scares you.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "If you want something you've never had, do something new.",
  "The only way out is through.",
  "You become what you think about.",
  "Excellence is never an accident.",
  "Fortune favors the bold.",
  "The best revenge is massive success.",
  "He who has a why can endure any how.",
  "You don't rise to the level of your goals.",
  "The mind is everything. What you think you become.",
  "Act, don't react.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Do the work. Especially when you don't feel like it.",
  "Hard choices, easy life.",
  "Suffer the pain of discipline or regret.",
  "If not now, when?",
  "What gets measured gets managed.",
  "You are what you repeatedly do.",
  "The obstacle is the way.",
  "Don't wish it were easier; wish you were better.",
  "Waste no more time arguing what a good man should be.",
  "To improve is to change.",
  "First we form habits, then they form us.",
  "You don't get what you want. You get what you work for.",
  "Luck is what happens when preparation meets opportunity.",
  "An ounce of action is worth a ton of theory.",
  "Fall seven times, stand up eight.",
  "Do today what others won't.",
  "The man who moves a mountain begins by carrying stones.",
  "If you want peace, prepare for war.",
  "No pressure, no diamonds.",
  "Be strict with yourself.",
  "Work hard in silence.",
  "Success is built daily.",
  "Don't count the days, make the days count.",
  "Decide. Commit. Execute.",
  "A year from now you may wish you had started today.",
  "Comfort is the enemy of progress.",
  "Great things are done by a series of small things.",
  "Do what is hard now so life is easy later.",
  "You can't escape the responsibility of tomorrow.",
  "If you're tired of starting over, stop quitting.",
  "Discipline equals freedom.",
  "What consumes your mind controls your life.",
  "Don't negotiate with weakness.",
  "The price of discipline is always less than regret.",
  "Master yourself.",
  "Earn your confidence.",
  "Sweat more in training, bleed less in battle.",
  "Do the difficult things while they are easy.",
  "A man conquers the world by conquering himself.",
  "Small disciplines repeated daily create big results.",
  "Success demands singleness of purpose.",
  "Your habits determine your future.",
  "The best project you'll ever work on is you.",
  "If you don't sacrifice for your goal, your goal becomes the sacrifice.",
  "Nothing great was ever achieved without discipline.",
  "Win the morning, win the day.",
  "Control your mind or it will control you."
];
